version: "3.8"

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    ports:
      - "8529:8529"
    volumes:
      - ./arango_data:/var/lib/arangodb3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_admin/server/availability"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit-ui:
    build: .
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      arangodb:
        condition: service_healthy
    volumes:
      - ./assets:/app/assets
      - ./data:/app/data  # optional: for raw CSVs or reference

  arangodb-setup:
    image: arangodb:latest
    container_name: arangodb-setup
    depends_on:
      arangodb:
        condition: service_healthy
    volumes:
      - ./init:/import
    entrypoint: >
      bash -c "
        echo '⏳ Waiting a few seconds for ArangoDB readiness...' &&
        sleep 5 &&
        echo '🚀 Executing create_schema.js' &&
        arangosh --server.endpoint http+tcp://arangodb:8529 \
                 --server.password openSesame \
                 --javascript.execute /import/create_schema.js
      "

  arangodb-load-data:
    image: arangodb:latest
    container_name: arangodb-load-data
    depends_on:
      arangodb-setup:
        condition: service_completed_successfully
    volumes:
      - ./init:/import
    entrypoint: >
      bash -c "
        echo '📦 Loading JSON data into ArangoDB...' &&
        arangosh --server.endpoint http+tcp://arangodb:8529 \
                 --server.password openSesame \
                 --javascript.execute /import/load_data.js
      "
